import { Roboto_Condensed } from 'next/font/google';

import './globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['300', '400', '700']
})

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={robotoCondensed.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
